plugin:
  has_options: false
  icon: res_file.png

  resources:
    - class: Innova\MediaBornageBundle\Entity\MediaResource
      name: innova_media_bornage
      is_exportable: false
      actions:
        - name: administrate
          menu_name: innova_media_resource_administrate
